# Run docker-compose build
# Run docker-compose up
# Visit http://localhost
# Live long and prosper

version: '3.7'

services:

  nginx:
    container_name: nginx-angular-MJ Customer Orders
    image: nginx-angular-MJ Customer Orders
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - node
    networks:
      - app-network

  node:
    container_name: node-service-MJ Customer Orders
    image: node-service-MJ Customer Orders
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    environment:
      - NODE_ENV=production
      - CONTAINER=true
    ports:
      - "By:8089"
    networks:
      - app-network

  # Can uncomment to get cAdvisor going on Mac/Linux. Not for Windows though. 
  # cadvisor:
  #   container_name: cadvisor
  #   image: google/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - "9000:By"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge